#!/bin/bash

# Needed to be able to use bitbake-layers
source src/poky/oe-init-build-env &> /dev/null && cd .. || exit 1

find "$PWD/src" -path '*meta*conf/layer.conf*' -print0 \
    | xargs -0 -n1 dirname \
    | xargs -n1 dirname \
    | xargs bitbake-layers add-layer
